apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: crypto-org
      defaultBucket: crypto_prices
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: true